spring.application.name=financiero

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://marlon1906ia_db_user:ddd6uSFYDQAJR37l@financiero.gdfpjlj.mongodb.net/sistemasfinanciero?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# Server Configuration
server.port=8080
server.servlet.context-path=/api/v1


